#!/usr/bin/env ruby -w

require 'yaml'

class QuestionStrategy
  attr_reader  :title

  def initialize(title, url='')
    @title = title
  end

  def run!
    questions = YAML.load(File.read(file_path))
    entry = {
      "title" => title,
      "date" => Time.now.strftime("%B %e, %Y")
    }

    if questions['entries'].nil?
      questions['entries'] = [entry]
    else
      questions['entries'] << entry
    end

      File.open(file_path, "w") do |f|
        f.write(YAML.dump questions)
      end
  end

  def file_path
    File.join(Dir.pwd, "/data/questions.yml")
  end
end

class LinkStrategy
  attr_reader  :title, :url

  def initialize(title, url)
    @title = title
    @url = url
  end

  def run!
    links = YAML.load(File.read(file_path))
    entry = {
      "title" => title,
      "date" => Time.now.strftime("%B %e, %Y"),
      "url" => url
    }

    if links['entries'].nil?
      links['entries'] = [entry]
    else
      links['entries'] << entry
    end

      File.open(file_path, "w") do |f|
        f.write(YAML.dump links)
      end
  end

  def file_path
    File.join(Dir.pwd, "/data/links.yml")
  end
end

class Application

  attr_reader :cmd

 DATA_SOURCES = {
   'li' => LinkStrategy,
   'q' => QuestionStrategy
 }
  def initialize(args)
    @cmd = args[0]
    @title = args[1]
    @url = args[2]
  end

  def run!
    class_name = DATA_SOURCES[cmd]
    if class_name.nil?
      puts "nasty message"
      exit
    end
    service = class_name.new @title, @url
    service.run!
  end
end

Application.new(ARGV).run!
# `bundle exec middleman deploy`
